### ISSUE TITLE
UBUNTU 24.04 LTS 

### ISSUE THREAD

**Issue by whackl** [boltgolt/howdy#890]
Hi there,
Ubuntu 24.04 lts is on its was,  will there be aversion for the New lts ?

**Comment by l3ifk** [comment]
Is there any update on this??

**Comment by l3ifk** [comment]
When adding the repository it says that the repository does not have a release file. When trying `sudo apt install howdy`, I get following output: 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package howdy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'howdy' has no installation candidate
```

**Comment by boltgolt** [comment]
Copied the package to Ubuntu Noble on launchpad, should be available within another hour or so. Thanks for reporting!

**Comment by l3ifk** [comment]
Thank you the install and setup works. Unfortunately my laptop does not try to use howdy even after a reboot.. It is enabled in PAM and I setup face models.
Also when using howdy test, I get a red circle around my face but never a green one. So it seems like howdy recognizes a face but not that it's mine? But I'm not sure about that one.

**Comment by l3ifk** [comment]
Also this error comes up during the install, I don't know if this causes a issues:
```
bind11::get_type_overload(const void*, const detail::type_info*, const char*)’:
/tmp/dlib-19.16/dlib/external/pybind11/include/pybind11/pybind11.h:1888:49: error: ‘PyThreadState’ {ak
a ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
 1888 |     PyFrameObject *frame = PyThreadState_Get()->frame;
      |                                                 ^~~~~
      |                                                 cframe
/tmp/dlib-19.16/dlib/external/pybind11/include/pybind11/pybind11.h:1889:41: error: invalid use of inco
mplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 1889 |     if (frame && (std::string) str(frame->f_code->co_name) == name &&
      |                                         ^~
/usr/include/python3.12/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct 
_frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/tmp/dlib-19.16/dlib/external/pybind11/include/pybind11/pybind11.h:1890:14: error: invalid use of inco
mplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 1890 |         frame->f_code->co_argcount > 0) {
      |              ^~
/usr/include/python3.12/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct 
_frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/tmp/dlib-19.16/dlib/external/pybind11/include/pybind11/pybind11.h:1893:18: error: invalid use of inco
mplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 1893 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
      |                  ^~
/usr/include/python3.12/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct 
_frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
In file included from /usr/include/python3.12/Python.h:38:
/tmp/dlib-19.16/dlib/external/pybind11/include/pybind11/pybind11.h:1893:52: error: invalid use of inco
mplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 1893 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
      |                                                    ^~

```

**Comment by aszabo70** [comment]
Hi, how did you install it on Ubuntu 24.04 with success? Because I have tried it according to description, added the repository, then after update I did install with apt, but at the end  I got the following error message: 
Sub-process /usr/bin/dpkg returned an error code (1)
Could somebody give me a detailed step by step howto?

**Comment by l3ifk** [comment]
> Hi, how did you install it on Ubuntu 24.04 with success? Because I have tried it according to description, added the repository, then after update I did install with apt, but at the end  I got the following error message: 
> Sub-process /usr/bin/dpkg returned an error code (1)
> Could somebody give me a detailed step by step howto?   

What else did it say before the last error. Could you give the whole error?

**Comment by aszabo70** [comment]
Yes

/var/lib/dpkg/info/howdy.postinst:145: SyntaxWarning: invalid escape sequence '\w'
  "davisking-dlib-\w+/(dlib/(http_client|java|matlab|test/)|"

>>> Upgrading pip to the latest version

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of
 breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error while running last command
dpkg: hiba a csomag feldolgozásakor: howdy (--configure):
 installed howdy package post-installation script subprocess returned error exit status 1

**Comment by enbzz** [comment]
I have successfully installed howdy on 24.04 such that the test and configuration works fine. 
I do see my face and the IR emitter is turned on. 
Although everything seems to be working, then howdy is not being used at login or for any operation requiring the password. Could 24.04 have changed something and forbid howdy to work correctly?

**Comment by cemoral** [comment]
I did a manual installation with meson and the packages that should be on global pip like this
`$ sudo pip install --break-system-packages dlib`

**Comment by enbzz** [comment]
> externally-managed-environment

I solved this by using: 
sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old

**Comment by l3ifk** [comment]
> I have successfully installed howdy on 24.04 such that the test and configuration works fine. I do see my face and the IR emitter is turned on. Although everything seems to be working, then howdy is not being used at login or for any operation requiring the password. Could 24.04 have changed something and forbid howdy to work correctly?

I have the exact same problem. Is there any fix for this? I already checked in `sudo pam-auth-update` and howdy is enabled there.

**Comment by aszabo70** [comment]
I could solve the issue but only with howdy_2.6.1.deb. I know this is a little bit old version but works.

**Comment by l3ifk** [comment]
unfortunately when trying to install the .deb you mentioned. It's just saying "preparing..." forever without actually installing anything...

**Comment by aszabo70** [comment]
Interesting, I had only one problem with ConfigParser in pam.py, it should be changed to configparser.
Some information regarding my system:

cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

cat /etc/debian_version 
trixie/sid

dpkg -l | grep howdy
ii  howdy                                 2.6.1                                    all          Howdy: Windows Hello style authentication for Linux.

dpkg -l | grep dlib
ii  libpython3-stdlib:amd64               3.12.3-0ubuntu1                          amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.12-stdlib:amd64            3.12.3-1                                 amd64        Interactive high-level object-oriented language (standard library, version 3.12)

I cannot give more info, sorry.

**Comment by Tegaf** [comment]
I manually installed the beta version `Howdy 3.0.0 BETA` on Ubuntu 24.04. Problem with
`No module named dlib`
    solved with:
`sudo pip install --break-system-packages dlib-bin`

**Comment by l3ifk** [comment]
Thanks for the suggesting but  I still get the same error while install howdy 3.0.0 BETA, even when trying to install the beta version.

**Comment by davclark** [comment]
The distro packagers put that EXTERNALLY-MANAGED file there to prevent anything other than apt/dpkg managing libraries installed in the system python. You can read about it here: https://packaging.python.org/en/latest/specifications/externally-managed-environments/

This is done to protect the system from breakage... ironically including security issues. So if you're thinking of moving that file, you can read more about what that actually does above.

**Comment by meetnick** [comment]
Did someone in this thread managed to get either sudo or gdm login screen working with howdy?

**Comment by Cerkal** [comment]
I was able to get it working by doing the following:

**Add repo:**
sudo add-apt-repository ppa:boltgolt/howdy

**Update:**
sudo apt update

**Install:**
sudo apt install howdy

**First install should error, install again:**
sudo apt install howdy

**Create link:**
sudo ln /lib/security/howdy/cli.py /usr/local/bin/howdy

**Tell cli.py the new working directory:**
sudo vim /lib/security/howdy/cli.py

_add after “import sys”_
sys.path.append('/lib/security/howdy')

**Install numpy:**
sudo apt install python3-numpy

**Install opencv:**
sudo apt install python3-opencv

**Install dlib:**
cd /tmp/
git clone https://github.com/davisking/dlib.git dlib
cd  dlib/
sudo python3 setup.py install

**Install v4-utils:**
sudo apt install v4l-utils
v4l2-ctl –list-devices

**Set device path in howdy config.ini:**
device_path = /dev/video2 [your camera device] 

**Edit sudo file to use howdy:**
sudo vim /etc/pam.d/sudo

_After #%PAM-1.0 comment_
auth sufficient pam_python.so /lib/security/howdy/pam.py
auth sufficient pam_unix.so try_first_pass likeauth nullok


**Fix pam:**
sudo vim  /usr/lib/security/howdy/pam.py

_Above config.read(os.path.dirname(os.path.abspath(__file__)) + "/config.ini") add:_
-------------------------------------------------------------------------------------
# PAM interface in python, launches compare.py

# Import required modules
import subprocess
import os
import glob
import syslog
import sys

# The config parser is named in python2 as ConfigParser but in python3 as configparser
# and here is a workaround for this.
if sys.version_info[0] == 2:
    import ConfigParser
    config = ConfigParser.ConfigParser()
else:
    import configparser
    config = configparser.ConfigParser()

_config.read(os.path.dirname(os.path.abspath(__file__)) + "/config.ini")_ 
-------------------------------------------------------------------------------------

**Get rid of any info logs if you are seeing them by adding this to your ~/.bashrc:**
export OPENCV_LOG_LEVEL=OFF
export GST_DEBUG=0

Hope this helps!

**Comment by cemoral** [comment]
Thanks for the working steps @Cerkal, however my terminal says `No face model known` even though I have face set. Do you know any solution for this ?

**Comment by Cerkal** [comment]
Hmm well it sound like its working at least. Confirm you have a .dat file in  `/usr/lib/security/howdy/models` it should be named the same as the username you created the model with. If its not there try creating a model again, make sure you are logged in as the user you want to use it as. If that doesn't work there was a suggestion on another forum to copy that file as root. `sudo cp /usr/lib/security/howdy/models/$USER.dat /usr/lib/security/howdy/models/root.dat`. Hope that works!

**Comment by cemoral** [comment]
@Cerkal it is strange that there was even no folder named models in `/usr/lib/security/howdy`. But I already have a face defined.. I created a models folder and readded my face but still doesn't work.
![image](https://github.com/boltgolt/howdy/assets/20835424/e11bf80e-d4de-495c-b933-2c2c623aa85e)

**Comment by Cerkal** [comment]
How about in `/usr/lib64/security/howdy/models` ?

**Comment by bernig** [comment]
@Cerkal Following your instructions, it now works perfectly, thanks a lot!

**Comment by thecalamityjoe87** [comment]
> Did someone in this thread managed to get either sudo or gdm login screen working with howdy?

I have this working on Ubuntu 24.04, even with GDM. Follow @Cerkal instructions and then edit `/etc/pam.d/gdm-password`. Add these lines to the bottom of that file:

```
auth sufficient pam_python.so /lib/security/howdy/pam.py
auth sufficient pam_unix.so try_first_pass likeauth nullok
```

**Comment by thecalamityjoe87** [comment]
I created a fork and fixed up v2.6.1 and created a new package to work with Ubuntu 24.04. I borrowed some help from @Cerkal and add some fixes myself. All the changes are located on my Github. If you'd like to try it out, follow these instructions.

Download the deb from here: https://github.com/thecalamityjoe87/howdy/releases/tag/v2.6.1-1

Make sure all deps are installed:
```

sudo apt-get update && sudo apt-get install -y \
python3 python3-pip python3-setuptools python3-wheel \
cmake make build-essential \
libpam0g-dev libinih-dev libevdev-dev \
python3-dev libopencv-dev python3-numpy \
python3-opencv libpam-python
```

Install the deb:

`sudo dpkg -i howdy_2.6.1-1_all.deb`

After setting up Howdy, you'll need to add the PAM module to `pam.d/sudo `and `pam.d/gdm-password`:

`sudo nano /etc/pam.d/sudo`

Add these lines:

```
auth sufficient pam_python.so /lib/security/howdy/pam.py
auth sufficient pam_unix.so try_first_pass likeauth nullok
```
Same thing for `gdm-password`:

`sudo nano /etc/pam.d/gdm-password`

Add these lines:

```
auth sufficient pam_python.so /lib/security/howdy/pam.py
auth sufficient pam_unix.so try_first_pass likeauth nullok
```

Lastly, we want to stop the DEBUG crap when Howdy is used:

`nano ~/.bashrc`

Add these lines:

```
export OPENCV_LOG_LEVEL=OFF
export GST_DEBUG=0

**Comment by diman82** [comment]
@thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?

**Comment by thecalamityjoe87** [comment]
> @thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?

If you followed the instructions from my comment, Howdy should be installed system-wide. You can follow the instructions on the main page for Howdy to configure it.

**Comment by diman82** [comment]
> > @thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?
> 
> If you followed the instructions from my comment, Howdy should be installed system-wide. You can follow the instructions on the main page for Howdy to configure it.

I've followed all instructions from the 'installation' comment, and I do even get randomly notifications like "No face model known", but _howdy_ command can't be found:
![image](https://github.com/user-attachments/assets/ea8cff9c-ae14-407c-81f2-ae164b64c8fb)

**Comment by thecalamityjoe87** [comment]
> > > @thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?
> > 
> > If you followed the instructions from my comment, Howdy should be installed system-wide. You can follow the instructions on the main page for Howdy to configure it.
> 
> I've followed all instructions from the 'installation' comment, and I do even get randomly notifications like "No face model known", but _howdy_ command can't be found:
> ![image](https://github.com/user-attachments/assets/ea8cff9c-ae14-407c-81f2-ae164b64c8fb)
> 

When you installed the deb, did it spit out any errors while installing? If you've checked for howdy in /usr/bin and confirm it's there, then some permissions got screwed up during post install of the deb.

**Comment by whizzi** [comment]
> > > > @thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?
> > > 
> > > 
> > > If you followed the instructions from my comment, Howdy should be installed system-wide. You can follow the instructions on the main page for Howdy to configure it.
> > 
> > 
> > I've followed all instructions from the 'installation' comment, and I do even get randomly notifications like "No face model known", but _howdy_ command can't be found:
> > ![image](https://private-user-images.githubusercontent.com/17273166/370194686-ea8cff9c-ae14-407c-81f2-ae164b64c8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTQ5MjQsIm5iZiI6MTcyNzI1NDYyNCwicGF0aCI6Ii8xNzI3MzE2Ni8zNzAxOTQ2ODYtZWE4Y2ZmOWMtYWUxNC00MDdjLTgxZjItYWUxNjRiNjRjOGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4NTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzU5NDE5NzZlOGE3ZDllMTgwYmU4ZTYxZTYxY2I1MmFkMTA4ZTVkZDliNjRhYzkxZjNjZjliYmZhYjZiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8BPoSgAjF2IHI_0bTCLmkhYIyEdRLJJE2YBIaWrZ-UA)
> 
> When you installed the deb, did it spit out any errors while installing? If you've checked for howdy in /usr/bin and confirm it's there, then some permissions got screwed up during post install of the deb.

I just downloaded the .deb and have the same problem. Apparently, it's not in the .deb provided: 
```
$ dpkg-deb --contents howdy_2.6.1-1_all.deb 
drwxr-xr-x root/root         0 2024-08-18 03:56 ./
drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/security/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/security/howdy/
drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/cli/
-rw-r--r-- root/root        34 2024-08-18 03:55 ./lib/security/howdy/cli/__init__.py
-rw-r--r-- root/root      5855 2024-08-18 03:55 ./lib/security/howdy/cli/add.py
-rw-r--r-- root/root      1004 2024-08-18 03:55 ./lib/security/howdy/cli/clear.py
-rw-r--r-- root/root       557 2024-08-18 03:55 ./lib/security/howdy/cli/config.py
-rw-r--r-- root/root      1462 2024-08-18 03:55 ./lib/security/howdy/cli/disable.py
-rw-r--r-- root/root      1376 2024-08-18 03:55 ./lib/security/howdy/cli/list.py
-rw-r--r-- root/root      2431 2024-08-18 03:55 ./lib/security/howdy/cli/remove.py
-rw-r--r-- root/root      1353 2024-08-18 03:55 ./lib/security/howdy/cli/snap.py
-rw-r--r-- root/root      6030 2024-08-18 03:55 ./lib/security/howdy/cli/test.py
-rwxr-xr-x root/root      3121 2024-08-18 03:55 ./lib/security/howdy/cli.py
-rw-r--r-- root/root      9306 2024-08-18 03:55 ./lib/security/howdy/compare.py
-rw-r--r-- root/root      2678 2024-08-18 03:55 ./lib/security/howdy/config.ini
drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/dlib-data/
-rw-r--r-- root/root        16 2024-08-18 03:55 ./lib/security/howdy/dlib-data/.gitignore
-rw-r--r-- root/root       412 2024-08-18 03:55 ./lib/security/howdy/dlib-data/Readme.md
-rwxr-xr-x root/root      1313 2024-08-18 03:55 ./lib/security/howdy/dlib-data/install.sh
-rw-r--r-- root/root      3068 2024-08-18 03:55 ./lib/security/howdy/logo.png
drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/pam-config/
-rw-r--r-- root/root       142 2024-08-18 03:55 ./lib/security/howdy/pam-config/howdy
-rw-r--r-- root/root      3839 2024-08-18 03:55 ./lib/security/howdy/pam.py
drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/recorders/
-rw-r--r-- root/root         0 2024-08-18 03:55 ./lib/security/howdy/recorders/__init__.py
-rw-r--r-- root/root      4700 2024-08-18 03:55 ./lib/security/howdy/recorders/ffmpeg_reader.py
-rw-r--r-- root/root      2900 2024-08-18 03:55 ./lib/security/howdy/recorders/pyv4l2_reader.py
-rw-r--r-- root/root     52253 2024-08-18 03:55 ./lib/security/howdy/recorders/v4l2.py
-rw-r--r-- root/root      3548 2024-08-18 03:55 ./lib/security/howdy/recorders/video_capture.py
-rw-r--r-- root/root      1835 2024-08-18 03:55 ./lib/security/howdy/snapshot.py
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/bash-completion/
drwxr-xr-x root/root         0 2024-08-18 03:55 ./usr/share/bash-completion/completions/
-rwxr-xr-x root/root      1090 2024-08-18 03:55 ./usr/share/bash-completion/completions/howdy
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/doc/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/doc/howdy/
-rw-r--r-- root/root      1339 2024-08-18 03:56 ./usr/share/doc/howdy/changelog.Debian.gz
-rw-r--r-- root/root      1065 2024-08-18 03:55 ./usr/share/doc/howdy/copyright
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/lintian/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/lintian/overrides/
-rw-r--r-- root/root       269 2024-08-18 03:55 ./usr/share/lintian/overrides/howdy
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/man/
drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/man/man1/
-rw-r--r-- root/root       557 2024-08-18 03:56 ./usr/share/man/man1/howdy.1.gz
drwxr-xr-x root/root         0 2024-08-18 03:55 ./usr/share/pam-configs/
-rw-r--r-- root/root       142 2024-08-18 03:55 ./usr/share/pam-configs/howdy
```

**Comment by thecalamityjoe87** [comment]
> > > > > @thecalamityjoe87 I've successfully followed the instructions above to install howdy from latest deb package, but how can I access howdy executable (it's not available system-wide)?
> > > > 
> > > > 
> > > > If you followed the instructions from my comment, Howdy should be installed system-wide. You can follow the instructions on the main page for Howdy to configure it.
> > > 
> > > 
> > > I've followed all instructions from the 'installation' comment, and I do even get randomly notifications like "No face model known", but _howdy_ command can't be found:
> > > ![image](https://private-user-images.githubusercontent.com/17273166/370194686-ea8cff9c-ae14-407c-81f2-ae164b64c8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTQ5MjQsIm5iZiI6MTcyNzI1NDYyNCwicGF0aCI6Ii8xNzI3MzE2Ni8zNzAxOTQ2ODYtZWE4Y2ZmOWMtYWUxNC00MDdjLTgxZjItYWUxNjRiNjRjOGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4NTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzU5NDE5NzZlOGE3ZDllMTgwYmU4ZTYxZTYxY2I1MmFkMTA4ZTVkZDliNjRhYzkxZjNjZjliYmZhYjZiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8BPoSgAjF2IHI_0bTCLmkhYIyEdRLJJE2YBIaWrZ-UA)
> > 
> > When you installed the deb, did it spit out any errors while installing? If you've checked for howdy in /usr/bin and confirm it's there, then some permissions got screwed up during post install of the deb.
> 
> I just downloaded the .deb and have the same problem. Apparently, it's not in the .deb provided: 
> ```
> $ dpkg-deb --contents howdy_2.6.1-1_all.deb 
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/security/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./lib/security/howdy/
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/cli/
> -rw-r--r-- root/root        34 2024-08-18 03:55 ./lib/security/howdy/cli/__init__.py
> -rw-r--r-- root/root      5855 2024-08-18 03:55 ./lib/security/howdy/cli/add.py
> -rw-r--r-- root/root      1004 2024-08-18 03:55 ./lib/security/howdy/cli/clear.py
> -rw-r--r-- root/root       557 2024-08-18 03:55 ./lib/security/howdy/cli/config.py
> -rw-r--r-- root/root      1462 2024-08-18 03:55 ./lib/security/howdy/cli/disable.py
> -rw-r--r-- root/root      1376 2024-08-18 03:55 ./lib/security/howdy/cli/list.py
> -rw-r--r-- root/root      2431 2024-08-18 03:55 ./lib/security/howdy/cli/remove.py
> -rw-r--r-- root/root      1353 2024-08-18 03:55 ./lib/security/howdy/cli/snap.py
> -rw-r--r-- root/root      6030 2024-08-18 03:55 ./lib/security/howdy/cli/test.py
> -rwxr-xr-x root/root      3121 2024-08-18 03:55 ./lib/security/howdy/cli.py
> -rw-r--r-- root/root      9306 2024-08-18 03:55 ./lib/security/howdy/compare.py
> -rw-r--r-- root/root      2678 2024-08-18 03:55 ./lib/security/howdy/config.ini
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/dlib-data/
> -rw-r--r-- root/root        16 2024-08-18 03:55 ./lib/security/howdy/dlib-data/.gitignore
> -rw-r--r-- root/root       412 2024-08-18 03:55 ./lib/security/howdy/dlib-data/Readme.md
> -rwxr-xr-x root/root      1313 2024-08-18 03:55 ./lib/security/howdy/dlib-data/install.sh
> -rw-r--r-- root/root      3068 2024-08-18 03:55 ./lib/security/howdy/logo.png
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/pam-config/
> -rw-r--r-- root/root       142 2024-08-18 03:55 ./lib/security/howdy/pam-config/howdy
> -rw-r--r-- root/root      3839 2024-08-18 03:55 ./lib/security/howdy/pam.py
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./lib/security/howdy/recorders/
> -rw-r--r-- root/root         0 2024-08-18 03:55 ./lib/security/howdy/recorders/__init__.py
> -rw-r--r-- root/root      4700 2024-08-18 03:55 ./lib/security/howdy/recorders/ffmpeg_reader.py
> -rw-r--r-- root/root      2900 2024-08-18 03:55 ./lib/security/howdy/recorders/pyv4l2_reader.py
> -rw-r--r-- root/root     52253 2024-08-18 03:55 ./lib/security/howdy/recorders/v4l2.py
> -rw-r--r-- root/root      3548 2024-08-18 03:55 ./lib/security/howdy/recorders/video_capture.py
> -rw-r--r-- root/root      1835 2024-08-18 03:55 ./lib/security/howdy/snapshot.py
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/bash-completion/
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./usr/share/bash-completion/completions/
> -rwxr-xr-x root/root      1090 2024-08-18 03:55 ./usr/share/bash-completion/completions/howdy
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/doc/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/doc/howdy/
> -rw-r--r-- root/root      1339 2024-08-18 03:56 ./usr/share/doc/howdy/changelog.Debian.gz
> -rw-r--r-- root/root      1065 2024-08-18 03:55 ./usr/share/doc/howdy/copyright
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/lintian/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/lintian/overrides/
> -rw-r--r-- root/root       269 2024-08-18 03:55 ./usr/share/lintian/overrides/howdy
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/man/
> drwxr-xr-x root/root         0 2024-08-18 03:56 ./usr/share/man/man1/
> -rw-r--r-- root/root       557 2024-08-18 03:56 ./usr/share/man/man1/howdy.1.gz
> drwxr-xr-x root/root         0 2024-08-18 03:55 ./usr/share/pam-configs/
> -rw-r--r-- root/root       142 2024-08-18 03:55 ./usr/share/pam-configs/howdy
> ```
> 

So, post install, a script is run to symlink cli.py to /usr/local/bin/howdy. If the DEB install fails, then that script won't get run. I had the location wrong, initially, but there should be a howdy symlink file in /usr/local/bin if Howdy was installed correctly.

**Comment by thecalamityjoe87** [comment]
> > So, post install, a script is run to symlink cli.py to /usr/local/bin/howdy. If the DEB install fails, then that script won't get run. I had the location wrong, initially, but there should be a howdy symlink file in /usr/local/bin if Howdy was installed correctly.
> 
> Ah, I figured out the problem. If the howdy package is installed from the repository, it doesn't show any errors but install is not completed. Removing the repository install and reinstalling the package from @thecalamityjoe87 works then.
> 
> I did have to change the device_path to /dev/video0 on my system in /usr/lib/security/howdy/config.ini .. 
> 
> I also added this to /etc/pam/auth-common instead of to only sudo and gdm-password:
> ```
> auth sufficient pam_python.so /lib/security/howdy/pam.py
> auth sufficient pam_unix.so try_first_pass likeauth nullok
> 
> ```
> Because I'm running Kubuntu . It now seems to work. Great job @thecalamityjoe87 !

Glad to hear that! I believe the necessity for setting your device_path is by design since it may be unique for your hardware.

Either way, I'm glad it's working for you.

**Comment by Geckuss** [comment]
@thecalamityjoe87 Thanks for the fixed version! I was able to get it to work, but not properly. Howdy would always scan my face twice, both times stating that unlock was succesful. I thought i must have messed something during the install, so i started again. During installation of .deb, i get lots of this kind of error:
In member function ‘allocate_array’,
    inlined from ‘set_max_size’ at /tmp/dlib-19.24.6/dlib/../dlib/matrix/../array/array_kernel.h:438:59,
    inlined from ‘resize’ at /tmp/dlib-19.24.6/dlib/../dlib/matrix/../array/array_kernel.h:654:30,
    inlined from ‘extract_image_chips.constprop.isra’ at /tmp/dlib-19.24.6/dlib/../dlib/image_transforms/interpolation.h:1891:21:
/tmp/dlib-19.24.6/dlib/../dlib/memory_manager_stateless/memory_manager_stateless_kernel_1.h:54:24: warning: argument 1 value ‘18446744073709551615’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   54 |                 return new T[size];
      |                        ^
/usr/include/c++/13/new: In function ‘extract_image_chips.constprop.isra’:
/usr/include/c++/13/new:128:26: note: in a call to allocation function ‘operator new []’ declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      | 
      
      Should i just ignore that?
      After all, it still says >>> Cleaning up dlib


>>> Configuring howdy

Camera ID saved
Permissions set
Howdy command installed

>>> Adding howdy as PAM module

Installation complete.

**Comment by thecalamityjoe87** [comment]
@Geckuss I don't think that warning matters. Did you configure your camera correctly via Howdy config?

Also, what are your PC specs?

**Comment by Geckuss** [comment]
I did configure it with the setup, and manually, both cause the same
result. I checked that it uses ir sensor as intended. I am using thinkpad
x1 gen 11 with integrated camera and ir sensor

pe 27. syysk. 2024 klo 16.38 Isaac ***@***.***> kirjoitti:

**Comment by FJ-RATO** [comment]
> I created a fork and fixed up v2.6.1 and created a new package to work with Ubuntu 24.04. I borrowed some help from @Cerkal and add some fixes myself. All the changes are located on my Github. If you'd like to try it out, follow these instructions.
> 
> Download the deb from here: https://github.com/thecalamityjoe87/howdy/releases/tag/v2.6.1-1
> 
> Make sure all deps are installed:
> 
> ```
> sudo apt-get update && sudo apt-get install -y \
> python3 python3-pip python3-setuptools python3-wheel \
> cmake make build-essential \
> libpam0g-dev libinih-dev libevdev-dev \
> python3-dev libopencv-dev python3-numpy \
> python3-opencv libpam-python
> ```
> 
> Install the deb:
> 
> `sudo dpkg -i howdy_2.6.1-1_all.deb`
> 
> After setting up Howdy, you'll need to add the PAM module to `pam.d/sudo `and `pam.d/gdm-password`:
> 
> `sudo nano /etc/pam.d/sudo`
> 
> Add these lines:
> 
> ```
> auth sufficient pam_python.so /lib/security/howdy/pam.py
> auth sufficient pam_unix.so try_first_pass likeauth nullok
> ```
> 
> Same thing for `gdm-password`. **This is so we can use Howdy on the login/lock screens**:
> 
> `sudo nano /etc/pam.d/gdm-password`
> 
> Add these lines:
> 
> ```
> auth sufficient pam_python.so /lib/security/howdy/pam.py
> auth sufficient pam_unix.so try_first_pass likeauth nullok
> ```
> 
> Lastly, we want to stop the DEBUG crap when Howdy is used:
> 
> `nano ~/.bashrc`
> 
> Add these lines:
> 
> ```
> export OPENCV_LOG_LEVEL=OFF
> export GST_DEBUG=0
> ```

Clean installed ubuntu 24.04 LTS and worked like a charm.

Just a note for people who aren't that bright like me, use howdy test to find out which camera is the IR camera

**Comment by mrugeshrocks** [comment]
> I created a fork and fixed up v2.6.1 and created a new package to work with Ubuntu 24.04. I borrowed some help from @Cerkal and add some fixes myself. All the changes are located on my Github. If you'd like to try it out, follow these instructions.
> 
> Download the deb from here: https://github.com/thecalamityjoe87/howdy/releases/tag/v2.6.1-1
> 
> Make sure all deps are installed:
> 
> ```
> sudo apt-get update && sudo apt-get install -y \
> python3 python3-pip python3-setuptools python3-wheel \
> cmake make build-essential \
> libpam0g-dev libinih-dev libevdev-dev \
> python3-dev libopencv-dev python3-numpy \
> python3-opencv libpam-python
> ```
> 
> Install the deb:
> 
> `sudo dpkg -i howdy_2.6.1-1_all.deb`
> 
> After setting up Howdy, you'll need to add the PAM module to `pam.d/sudo `and `pam.d/gdm-password`:
> 
> `sudo nano /etc/pam.d/sudo`
> 
> Add these lines:
> 
> ```
> auth sufficient pam_python.so /lib/security/howdy/pam.py
> auth sufficient pam_unix.so try_first_pass likeauth nullok
> ```
> 
> Same thing for `gdm-password`. **This is so we can use Howdy on the login/lock screens**:
> 
> `sudo nano /etc/pam.d/gdm-password`
> 
> Add these lines:
> 
> ```
> auth sufficient pam_python.so /lib/security/howdy/pam.py
> auth sufficient pam_unix.so try_first_pass likeauth nullok
> ```
> 
> Lastly, we want to stop the DEBUG crap when Howdy is used:
> 
> `nano ~/.bashrc`
> 
> Add these lines:
> 
> ```
> export OPENCV_LOG_LEVEL=OFF
> export GST_DEBUG=0
> ```

You are savior. worked like a charm thanks :)

**Comment by xhinker** [comment]
> > externally-managed-environment
> 
> I solved this by using: sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old

This is the SOLUTION

**Comment by blamairia** [comment]
I created an automated patcher that fixes this issue: https://github.com/blamairia/howdy-patcher

Just run: curl -fsSL https://raw.githubusercontent.com/blamairia/howdy-patcher/main/howdy-patcher.sh | sudo bash

**Comment by jatroconis** [comment]
For anyone landing here from a search for Ubuntu 24.04 (noble), Zorin OS 18, Linux Mint 22, or Pop!_OS 24.04 — I just published a script that handles the full install end-to-end, including all the patches the broken postinst skips:

**https://github.com/jatroconis/howdy-noble-setup**

```bash
curl -fsSL https://raw.githubusercontent.com/jatroconis/howdy-noble-setup/main/setup-howdy-noble.sh -o setup-howdy-noble.sh
less setup-howdy-noble.sh        # always read scripts before piping to sudo
sudo bash setup-howdy-noble.sh
```

It's idempotent and auto-detects the IR camera. Beyond the [@blamairia](https://github.com/blamairia) patches (`ConfigParser`, V4L2 backend, `dlib --break-system-packages`), it also fixes:

- `pam.py` `subprocess.call` is missing `cwd` and `PYTHONPATH` → `compare.py` raises `ModuleNotFoundError: No module named 'recorders.video_capture'` at every `sudo` invocation, even when face auth eventually succeeds via fallback. Patched to set both env vars and silence stdout/stderr so the trace doesn't leak into terminal output.
- `compare.py` needs a `sys.path.insert` at the top so its sibling imports work under PAM (belt-and-suspenders alongside the `pam.py` fix).
- The existing V4L2 regex in `howdy-patcher` matches `os.path.exists()` instead of `cv2.VideoCapture()` on v2.6.1 — both call `self.config.get("video", "device_path")`, but `os.path.exists` only takes one argument so the wrong patch breaks `video_capture.py`. The new script does an exact-block match.
- The postinst's `chmod 744 -R` strips the `x` bit from directories so PAM's subprocess can't traverse `recorders/`, `cli/`, etc. The script restores `755` on dirs.

I also fed those four fixes back upstream as PRs:
- [blamairia/howdy-patcher#1](https://github.com/blamairia/howdy-patcher/pull/1) — extends the patcher with the new fixes
- [boltgolt/howdy#1110](https://github.com/boltgolt/howdy/pull/1110) — docs PR adding ASUS hardware notes
- [boltgolt/howdy#1109](https://github.com/boltgolt/howdy/issues/1109) — explains why the IR feed looks "dead" on ASUS Sonix `3277:0018` (Vivobook X1607C, ProArt PX13 / H7606WX, Zenbook S16 UM5606): the LED is gated by the laptop's proximity sensor, not by a UVC control. **Do not run `linux-enable-ir-emitter configure` on these models** — its brute-force step has wedged the USB bus on Sonix chips for me and others, requiring a hard reboot.

Tested end-to-end on Zorin OS 18 with an ASUS X1607C. Final state: `sudo -k && sudo whoami` shows `Identified face as <user>` and returns root without a password prompt, no traceback noise.

Hope this saves someone the debug session. Happy to take feedback on the script.
